// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4vclogit_l2_type1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4vclogit_l2_type2_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4vclogit_l2_type3_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4vclogit_l2_type4_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4vclogit_l2_type5_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4vclogit_l2_type6_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4vclogit_l2_type7_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4vclogit_l2_type8_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4vclogit_l2_type1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4vclogit_l2_type1_mod, 0},
    {"_rcpp_module_boot_stan_fit4vclogit_l2_type2_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4vclogit_l2_type2_mod, 0},
    {"_rcpp_module_boot_stan_fit4vclogit_l2_type3_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4vclogit_l2_type3_mod, 0},
    {"_rcpp_module_boot_stan_fit4vclogit_l2_type4_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4vclogit_l2_type4_mod, 0},
    {"_rcpp_module_boot_stan_fit4vclogit_l2_type5_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4vclogit_l2_type5_mod, 0},
    {"_rcpp_module_boot_stan_fit4vclogit_l2_type6_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4vclogit_l2_type6_mod, 0},
    {"_rcpp_module_boot_stan_fit4vclogit_l2_type7_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4vclogit_l2_type7_mod, 0},
    {"_rcpp_module_boot_stan_fit4vclogit_l2_type8_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4vclogit_l2_type8_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_voteswitchR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
