#' @title Recode aggregate switching patterns
#'
#' @description Recodes raw aggregate switching patterns according to a
#' user-supplied factor variable included in a (possibly user-supplied) version
#' of \code{mappings}.
#'
#' @param switches Aggregate counts of switches as generated by
#' [build_data_file()].
#' @param subgroup A character that specifies the column-name of electorate
#' subgroups. Should be \code{NULL} (the default) if no subgroup analyses are
#' required.
#' @param stack_by_subgroup Logical; if \code{TRUE}, subgroups are stacked into
#' long format such that switching proportions from the MAVCL model sum to one
#' within subgroups.
#' If \code{FALSE}, subgroup-specific switching is recorded in wide format such
#' that switching proportions for each subgroup sum to the size of the subgroup.
#' Only takes effect if \code{subgroup != NULL}.
#' @param assign_others Optional: A character that specifies a level for
#' residual other parties for which \code{switch_factor} information is not
#' available.
#' @param mappings A copy of [mappings], possibly
#' enriched with external party and/or election-specific variables.
#' @param switch_factor Column name of a factor variable in \code{mappings}
#' that specifies the marginal categories of the desired voter transition
#' matrix.
#' @param type Specifies whether to return election-specific voter-transition
#' matrices (\code{"elections"}) or stacked party-within-election transition
#' matrices (\code{"party-elections"}). The latter
#' should be used for studying the effects of party strategies.
#'
#' @return Returns the supplied data frame \code{mappings}, extended by columns
#' for each switching pattern detected in the data.
#'
#' @export

recode_switches <- function(switches,
                            subgroup = NULL,
                            stack_by_subgroup = FALSE,
                            assign_others = NULL,
                            mappings = NULL,
                            switch_factor,
                            type = c("elections", "party-elections")) {

  ## ---- Preparation ----
  ## No summarize info
  options(dplyr.summarise.inform = FALSE)

  ## switch_factor as character
  mappings[[switch_factor]] <-
    as.factor(mappings[[switch_factor]]) %>%
    droplevels() %>%
    as.character()

  ## assign residual parties to distrinct category?
  val98 <- ifelse(is.null(assign_others), "oth", assign_others)

  ## Check for missingness in switch_factor
  if (any(is.na(mappings[[switch_factor]]))) {
    warning(
      paste(
        "'switch_factor' contains NAs.",
        "These will be subsumed under 'Others' (oth).",
        sep = " "
      )
    )
    mappings[[switch_factor]] <-
      ifelse(is.na(mappings[[switch_factor]]),
        "oth",
        mappings[[switch_factor]]
      )
  }

  ## Determine party-level variables in mappings
  if (type == "elections") {
    peid_vars <- mappings %>%
      dplyr::group_by(elec_id) %>%
      dplyr::summarize_all(.funs = ~ length(unique(.))) %>%
      dplyr::ungroup() %>%
      dplyr::summarize_if(is.numeric, .funs = ~ max(., na.rm = TRUE)) %>%
      as.matrix()
    peid_vars <- colnames(peid_vars)[peid_vars[1, ] != 1]
  }

  ## ---- Recoding of switches ----
  ## Augment switching
  switches <- switches %>%
    dplyr::filter(elec_id %in% mappings$elec_id) %>%
    dplyr::left_join(
      mappings %>%
        dplyr::rename(from = !!as.name(switch_factor)) %>%
        dplyr::select(elec_id, stack, from),
      by = c("elec_id", "switch_from" = "stack")
    ) %>%
    dplyr::left_join(
      mappings %>%
        dplyr::rename(to = !!as.name(switch_factor)) %>%
        dplyr::select(elec_id, stack, to),
      by = c("elec_id", "switch_to" = "stack")
    ) %>%
    dplyr::mutate(
      from = dplyr::case_when(
        switch_from == 98 ~ val98,
        switch_from == 99 ~ "non",
        is.na(from) ~ val98,
        TRUE ~ from
      ),
      to = dplyr::case_when(
        switch_to == 98 ~ val98,
        switch_to == 99 ~ "non",
        is.na(to) ~ val98,
        TRUE ~ to
      )
    )

  ## ---- Aggregation at chosen level ----
  if (is.null(subgroup)) {
    if (type == "elections") {
      ## Define y_structure and y_names
      y_structure <- switches %>%
        dplyr::select(from, to) %>%
        dplyr::distinct() %>%
        dplyr::mutate(cat = from) %>%
        tidyr::expand(cat, from, to) %>%
        dplyr::mutate(switch = paste(from, to, sep = "_")) %>%
        dplyr::mutate(
          type = dplyr::case_when(
            cat == from & cat == to ~ "retain",
            cat == from & cat != to ~ "loss",
            cat != from & cat == to ~ "gain",
            TRUE ~ "resid"
          )
        ) %>%
        dplyr::mutate(dyad = dplyr::case_when(
          type == "loss" ~ to,
          type == "gain" ~ from,
          TRUE ~ NA_character_
        )) %>%
        dplyr::select(-from, -to) %>%
        split(., .$cat) %>%
        lapply(., function(x) {
          x %>% dplyr::mutate(pos = dplyr::row_number())
        })
      y_names <- y_structure[[1]]$switch

      ## Election-level switches
      elec_switches <- switches %>%
        dplyr::group_by(elec_id) %>%
        dplyr::mutate(switch = paste(from, to, sep = "_")) %>%
        dplyr::group_by(elec_id, switch) %>%
        dplyr::summarize(weights = dplyr::if_else(all(is.na(weights)),
          NA_real_,
          sum(weights, na.rm = TRUE)
        )) %>%
        dplyr::mutate(weights = ifelse(is.na(weights), -1.0, weights)) %>%
        tidyr::pivot_wider(
          names_from = "switch",
          values_from = weights
        ) %>%
        dplyr::mutate_if(is.numeric,
          .funs = ~ ifelse(is.na(.), -1.0, .)
        )

      ## Output
      output <- list(
        data = mappings %>%
          dplyr::select(
            -dplyr::all_of(peid_vars), -dplyr::any_of(switch_factor)
          ) %>%
          dplyr::distinct() %>%
          dplyr::inner_join(elec_switches,
            by = c("elec_id")
          ),
        y_names = y_names,
        y_structure = y_structure
      )
    } else if (type == "party-elections") {
      ## Party-election level switches
      peid_switches <- switches %>%
        dplyr::left_join(mappings %>%
          dplyr::select(elec_id, stack),
        by = "elec_id"
        ) %>%
        dplyr::group_by(elec_id, stack) %>%
        dplyr::mutate(
          to = ifelse(switch_to == stack, "party", to),
          from = ifelse(switch_from == stack, "party", from),
          switch = case_when(
            switch_from == stack & switch_to == stack ~ "retention",
            switch_from != stack & switch_to != stack ~ "residual",
            TRUE ~ paste(from, to, sep = "_")
          )
        ) %>%
        dplyr::group_by(elec_id, stack, switch) %>%
        dplyr::summarize(
          from = unique(from),
          to = unique(to),
          weights = dplyr::if_else(all(is.na(weights)),
            NA_real_,
            sum(weights, na.rm = TRUE)
          )
        ) %>%
        dplyr::ungroup() %>%
        dplyr::mutate(weights = ifelse(is.na(weights), -1.0, weights))

      ## Define y_structure and y_names
      y_structure <- peid_switches %>%
        dplyr::select(from, to, switch) %>%
        dplyr::distinct() %>%
        dplyr::mutate(
          type = dplyr::case_when(
            from == "party" & to == "party" ~ "retain",
            from == "party" & to != "party" ~ "loss",
            from != "party" & to == "party" ~ "gain",
            TRUE ~ "resid"
          )
        ) %>%
        dplyr::mutate(dyad = dplyr::case_when(
          type == "loss" ~ to,
          type == "gain" ~ from,
          TRUE ~ NA_character_
        )) %>%
        dplyr::select(-to, -from) %>%
        dplyr::distinct() %>%
        dplyr::arrange(!(is.na(dyad)), type, dyad) %>%
        dplyr::mutate(pos = dplyr::row_number())
      y_names <- y_structure$switch

      peid_switches <- peid_switches %>%
        dplyr::select(-to, -from) %>%
        dplyr::distinct() %>%
        tidyr::pivot_wider(
          names_from = "switch",
          values_from = weights
        ) %>%
        dplyr::mutate_if(is.numeric,
          .funs = ~ ifelse(is.na(.), -1.0, .)
        )

      ## Output
      output <- list(
        data = mappings %>%
          dplyr::inner_join(peid_switches,
            by = c("elec_id", "stack")
          ),
        y_names = y_names,
        y_structure = y_structure
      )
    }
  } else {
    if (stack_by_subgroup) {
      if (type == "elections") {
        ## Define y_structure and y_names
        y_structure <- switches %>%
          dplyr::select(from, to) %>%
          dplyr::distinct() %>%
          dplyr::mutate(cat = from) %>%
          tidyr::expand(cat, from, to) %>%
          dplyr::mutate(switch = paste(from, to, sep = "_")) %>%
          dplyr::mutate(
            type = dplyr::case_when(
              cat == from & cat == to ~ "retain",
              cat == from & cat != to ~ "loss",
              cat != from & cat == to ~ "gain",
              TRUE ~ "resid"
            )
          ) %>%
          dplyr::mutate(dyad = dplyr::case_when(
            type == "loss" ~ to,
            type == "gain" ~ from,
            TRUE ~ NA_character_
          )) %>%
          dplyr::select(-from, -to) %>%
          split(., .$cat) %>%
          lapply(., function(x) {
            x %>% dplyr::mutate(pos = dplyr::row_number())
          })
        y_names <- y_structure[[1]]$switch

        ## Election-group-level switches
        elec_switches <- switches %>%
          dplyr::mutate(elec_group_id = paste(elec_id, !!as.name(subgroup),
                                              sep = "-")) %>%
          dplyr::group_by(elec_id, elec_group_id) %>%
          dplyr::mutate(switch = paste(from, to, sep = "_")) %>%
          dplyr::group_by(elec_id, elec_group_id, switch) %>%
          dplyr::summarize(
            weights = dplyr::if_else(all(is.na(weights)),
              NA_real_,
              sum(weights, na.rm = TRUE)
            ),
            subgroup = unique(!!as.name(subgroup))
          ) %>%
          dplyr::mutate(weights = ifelse(is.na(weights), -1.0, weights)) %>%
          tidyr::pivot_wider(
            names_from = "switch",
            values_from = weights
          ) %>%
          dplyr::mutate_if(is.numeric,
            .funs = ~ ifelse(is.na(.), -1.0, .)
          )

        ## Output
        output <- list(
          data = mappings %>%
            dplyr::select(
              -dplyr::all_of(peid_vars), -dplyr::any_of(switch_factor)
            ) %>%
            dplyr::distinct() %>%
            dplyr::inner_join(elec_switches,
              by = c("elec_id")
            ),
          y_names = y_names,
          y_structure = y_structure
        )
      } else if (type == "party-elections") {
        ## Party-election level switches
        peid_switches <- switches %>%
          dplyr::mutate(elec_group_id = paste(elec_id, !!as.name(subgroup),
                                              sep = "-")) %>%
          dplyr::left_join(mappings %>%
            dplyr::select(elec_id, stack),
          by = "elec_id"
          ) %>%
          dplyr::group_by(elec_id, elec_group_id, stack) %>%
          dplyr::mutate(
            to = ifelse(switch_to == stack, "party", to),
            from = ifelse(switch_from == stack, "party", from),
            switch = case_when(
              switch_from == stack & switch_to == stack ~ "retention",
              switch_from != stack &
                switch_to != stack ~ "residual",
              TRUE ~ paste(from, to, sep = "_")
            )
          ) %>%
          dplyr::group_by(elec_id, elec_group_id, stack, switch) %>%
          dplyr::summarize(
            from = unique(from),
            to = unique(to),
            subgroup = unique(!!as.name(subgroup)),
            weights = dplyr::if_else(all(is.na(weights)),
              NA_real_,
              sum(weights, na.rm = TRUE)
            )
          ) %>%
          dplyr::ungroup() %>%
          dplyr::mutate(weights = ifelse(is.na(weights), -1.0, weights))

        ## Define y_structure and y_names
        y_structure <- peid_switches %>%
          dplyr::select(from, to, switch) %>%
          dplyr::distinct() %>%
          dplyr::mutate(
            type = dplyr::case_when(
              from == "party" & to == "party" ~ "retain",
              from == "party" & to != "party" ~ "loss",
              from != "party" & to == "party" ~ "gain",
              TRUE ~ "resid"
            )
          ) %>%
          dplyr::mutate(dyad = dplyr::case_when(
            type == "loss" ~ to,
            type == "gain" ~ from,
            TRUE ~ NA_character_
          )) %>%
          dplyr::select(-to, -from) %>%
          dplyr::distinct() %>%
          dplyr::arrange(!(is.na(dyad)), type, dyad) %>%
          dplyr::mutate(pos = dplyr::row_number())
        y_names <- y_structure$switch

        peid_switches <- peid_switches %>%
          dplyr::select(-to, -from) %>%
          dplyr::distinct() %>%
          tidyr::pivot_wider(
            names_from = "switch",
            values_from = weights
          ) %>%
          dplyr::mutate_if(is.numeric,
            .funs = ~ ifelse(is.na(.), -1.0, .)
          )

        ## Output
        output <- list(
          data = mappings %>%
            dplyr::inner_join(peid_switches,
              by = c("elec_id", "stack")
            ),
          y_names = y_names,
          y_structure = y_structure
        )
      }
    } else {
      if (type == "elections") {
        ## Define y_structure and y_names
        y_structure <- switches %>%
          dplyr::select(from, to, !!as.name(subgroup)) %>%
          dplyr::distinct() %>%
          dplyr::mutate(cat = from) %>%
          tidyr::expand(cat, from, to, !!as.name(subgroup)) %>%
          dplyr::mutate(switch = paste(from, to, !!as.name(subgroup),
                                       sep = "_")) %>%
          dplyr::mutate(
            type = dplyr::case_when(
              cat == from & cat == to ~ "retain",
              cat == from & cat != to ~ "loss",
              cat != from & cat == to ~ "gain",
              TRUE ~ "resid"
            )
          ) %>%
          dplyr::mutate(dyad = dplyr::case_when(
            type == "loss" ~ to,
            type == "gain" ~ from,
            TRUE ~ NA_character_
          )) %>%
          dplyr::select(-from, -to) %>%
          split(., .$cat) %>%
          lapply(., function(x) {
            x %>% dplyr::mutate(pos = dplyr::row_number())
          })
        y_names <- y_structure[[1]]$switch

        ## Election-level switches
        elec_switches <- switches %>%
          dplyr::group_by(elec_id, !!as.name(subgroup)) %>%
          dplyr::mutate(switch = paste(from, to, !!as.name(subgroup),
                                       sep = "_")) %>%
          dplyr::group_by(elec_id, !!as.name(subgroup), switch) %>%
          dplyr::summarize(weights = dplyr::if_else(all(is.na(weights)),
            NA_real_,
            sum(weights, na.rm = TRUE)
          )) %>%
          dplyr::mutate(weights = ifelse(is.na(weights), -1.0, weights)) %>%
          tidyr::pivot_wider(
            names_from = "switch",
            values_from = weights
          ) %>%
          dplyr::mutate_if(is.numeric,
            .funs = ~ ifelse(is.na(.), -1.0, .)
          )

        ## Output
        output <- list(
          data = mappings %>%
            dplyr::select(
              -dplyr::all_of(peid_vars), -dplyr::any_of(switch_factor)
            ) %>%
            dplyr::distinct() %>%
            dplyr::inner_join(elec_switches,
              by = c("elec_id")
            ),
          y_names = y_names,
          y_structure = y_structure
        )
      } else if (type == "party-elections") {
        ## Party-election level switches
        peid_switches <- switches %>%
          dplyr::left_join(mappings %>%
            dplyr::select(elec_id, stack),
          by = "elec_id"
          ) %>%
          dplyr::group_by(elec_id, !!as.name(subgroup), stack) %>%
          dplyr::mutate(
            to = ifelse(switch_to == stack, "party", to),
            from = ifelse(switch_from == stack, "party", from),
            switch = case_when(
              switch_from == stack & switch_to == stack ~ "retention",
              switch_from != stack &
                switch_to != stack ~ "residual",
              TRUE ~ paste(from, to, sep = "_")
            )
          ) %>%
          dplyr::group_by(elec_id, !!as.name(subgroup), stack, switch) %>%
          dplyr::summarize(
            from = unique(from),
            to = unique(to),
            weights = dplyr::if_else(all(is.na(weights)),
              NA_real_,
              sum(weights, na.rm = TRUE)
            )
          ) %>%
          dplyr::ungroup() %>%
          dplyr::mutate(weights = ifelse(is.na(weights), -1.0, weights))

        ## Define y_structure and y_names
        y_structure <- peid_switches %>%
          dplyr::select(from, to, switch) %>%
          dplyr::distinct() %>%
          dplyr::mutate(
            type = dplyr::case_when(
              from == "party" & to == "party" ~ "retain",
              from == "party" & to != "party" ~ "loss",
              from != "party" & to == "party" ~ "gain",
              TRUE ~ "resid"
            )
          ) %>%
          dplyr::mutate(dyad = dplyr::case_when(
            type == "loss" ~ to,
            type == "gain" ~ from,
            TRUE ~ NA_character_
          )) %>%
          dplyr::select(-to, -from) %>%
          dplyr::distinct() %>%
          dplyr::arrange(!(is.na(dyad)), type, dyad) %>%
          dplyr::mutate(pos = dplyr::row_number())
        y_names <- y_structure$switch

        peid_switches <- peid_switches %>%
          dplyr::select(-to, -from) %>%
          dplyr::distinct() %>%
          tidyr::pivot_wider(
            names_from = "switch",
            values_from = weights
          ) %>%
          dplyr::mutate_if(is.numeric,
            .funs = ~ ifelse(is.na(.), -1.0, .)
          )

        ## Output
        output <- list(
          data = mappings %>%
            dplyr::inner_join(peid_switches,
              by = c("elec_id", "stack")
            ),
          y_names = y_names,
          y_structure = y_structure
        )
      }
    }
  }

  ## ---- Return ----
  return(output)
}
