# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("vclogit_l2_type1", "vclogit_l2_type2", "vclogit_l2_type3", "vclogit_l2_type4", "vclogit_l2_type5", "vclogit_l2_type6", "vclogit_l2_type7", "vclogit_l2_type8")

# load each stan module
Rcpp::loadModule("stan_fit4vclogit_l2_type1_mod", what = TRUE)
Rcpp::loadModule("stan_fit4vclogit_l2_type2_mod", what = TRUE)
Rcpp::loadModule("stan_fit4vclogit_l2_type3_mod", what = TRUE)
Rcpp::loadModule("stan_fit4vclogit_l2_type4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4vclogit_l2_type5_mod", what = TRUE)
Rcpp::loadModule("stan_fit4vclogit_l2_type6_mod", what = TRUE)
Rcpp::loadModule("stan_fit4vclogit_l2_type7_mod", what = TRUE)
Rcpp::loadModule("stan_fit4vclogit_l2_type8_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
